### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by joshjau** [Aeon234/AdvancedMythicTracker#1]
Hello,

Just reporting some bug code i keep receiving with your addon. Btw it is great! Keep up the work overall.

`1x AdvancedMythicTracker/Display.lua:1355: attempt to perform arithmetic on field '?' (a nil value)
[string "@AdvancedMythicTracker/Display.lua"]:1355: in function `?'
[string "@AdvancedMythicTracker/Display.lua"]:1232: in function `AMT_Creation'
[string "@AdvancedMythicTracker/Main.lua"]:106: in function <AdvancedMythicTracker/Main.lua:97>
[string "=[C]"]: in function `Show'
[string "@AdvancedMythicTracker/Main.lua"]:49: in function <AdvancedMythicTracker/Main.lua:43>

Locals:
self = <table> {
 Tab = "          "
 BackgroundClear = <table> {
 }
 ElvUIEnabled = false
 Vault_BoxSize = 14
 Keystone_Modifiers = <table> {
 }
 Keystone_Icon = "AdvancedMythicTracker/Media/Icons/Keystone_Hourglass"
 IsGame_10_2_0 = true
 PVEFrame_Panels = <table> {
 }
 API = <table> {
 }
 Whitetext = "|cffffffff"
 RunHistory = <table> {
 }
 AMT_Font = "AdvancedMythicTracker/Media/Fonts/Expressway.TTF"
 Player_Mplus_ScoreColor = <table> {
 }
 db = <table> {`

**Comment by Aeon234** [comment]
Hey, thanks for the report!

I've actually been going through and resolving all of these bugs for past few hours. Most of them are squashed. I have to finish up a few more things tonight and tomorrow morning I'll be pushing out a new update. The fix for this will be included in there.

**Comment by Aeon234** [comment]
Just pushed out an update. Should be live on Cursforge in a few minutes.

**Comment by joshjau** [comment]
> Just pushed out an update. Should be live on Cursforge in a few minutes.

sorry failed to get back to you, the issue was fixed. keep up the good work.

**Comment by Aeon234** [comment]
All good, I assumed since you didn't get back that the problem was resolved.
